// --- taskit-managed module ---
//! Taskit command adapter generated by `taskit init`.

pub(super) fn dispatch() -> bool {
    let task = std::env::args().nth(1).unwrap_or_default();
    let args: &[&str] = match task.as_str() {
        "fmt" => &["fmt"],
        "fmt-check" => &["fmt", "--check"],
        "lint" => &["lint"],
        "test" => &["test"],
        "ci" => &["ci"],
        "pre-commit" => &["pre-commit"],
        "pre-push" => &["pre-push"],
        _ => return false,
    };

    taskit(args);
    true
}

fn taskit(args: &[&str]) {
    let status = match std::process::Command::new("taskit").args(args).status() {
        Ok(status) => status,
        Err(_) => match std::process::Command::new("cargo")
            .args(["run", "-p", "taskit", "--"])
            .args(args)
            .status()
        {
            Ok(status) => status,
            Err(err) => {
                eprintln!("failed to run taskit via binary or cargo fallback: {err}");
                std::process::exit(1);
            }
        },
    };
    if !status.success() {
        std::process::exit(status.code().unwrap_or(1));
    }
}
// --- end taskit-managed module ---
