// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class types.

use super::*;
use baml::{BamlDecode, BamlEncode};

/// A single file with merge conflicts awaiting resolution.

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ConflictInput {
    pub path: String,

    pub ours: String,

    pub theirs: String,

    pub base: Option<String>,
}

impl AsRef<ConflictInput> for ConflictInput {
    fn as_ref(&self) -> &ConflictInput {
        self
    }
}

/// Outcome for a batch of conflicts.

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ConflictResolution {
    pub resolved: Vec<ResolvedConflict>,

    pub needs_human: Vec<String>,
}

impl AsRef<ConflictResolution> for ConflictResolution {
    fn as_ref(&self) -> &ConflictResolution {
        self
    }
}

/// A file with its conflict fully resolved.

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ResolvedConflict {
    pub path: String,

    pub content: String,

    pub confidence: f64,

    pub rationale: String,
}

impl AsRef<ResolvedConflict> for ResolvedConflict {
    fn as_ref(&self) -> &ResolvedConflict {
        self
    }
}
