// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming class types.
//!
//! These types are used during streaming to hold partial results.
//! Field types are already wrapped appropriately (Option, StreamState, etc.)

use super::*;
use crate::baml_client::types;
use baml::BamlDecode;

/// A single file with merge conflicts awaiting resolution.

#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ConflictInput {
    pub path: Option<String>,

    pub ours: Option<String>,

    pub theirs: Option<String>,

    pub base: Option<String>,
}

impl AsRef<ConflictInput> for ConflictInput {
    fn as_ref(&self) -> &ConflictInput {
        self
    }
}

/// Outcome for a batch of conflicts.

#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ConflictResolution {
    pub resolved: Vec<ResolvedConflict>,

    pub needs_human: Vec<String>,
}

impl AsRef<ConflictResolution> for ConflictResolution {
    fn as_ref(&self) -> &ConflictResolution {
        self
    }
}

/// A file with its conflict fully resolved.

#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ResolvedConflict {
    pub path: Option<String>,

    pub content: Option<String>,

    pub confidence: Option<f64>,

    pub rationale: Option<String>,
}

impl AsRef<ResolvedConflict> for ResolvedConflict {
    fn as_ref(&self) -> &ResolvedConflict {
        self
    }
}
