// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class builder wrappers for type-safe field access.

/// Wrapper for the `ConflictInput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ConflictInputClassBuilder {
    inner: baml::ClassBuilder,
}

impl ConflictInputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner
            .as_type()
            .expect("ConflictInput is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `path` field builder.
    pub fn property_path(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("path").expect(
            "ConflictInput.path is statically defined in .baml and should always be present",
        )
    }

    /// Access the `ours` field builder.
    pub fn property_ours(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("ours").expect(
            "ConflictInput.ours is statically defined in .baml and should always be present",
        )
    }

    /// Access the `theirs` field builder.
    pub fn property_theirs(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("theirs").expect(
            "ConflictInput.theirs is statically defined in .baml and should always be present",
        )
    }

    /// Access the `base` field builder.
    pub fn property_base(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("base").expect(
            "ConflictInput.base is statically defined in .baml and should always be present",
        )
    }
}

/// Wrapper for the `ConflictResolution` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ConflictResolutionClassBuilder {
    inner: baml::ClassBuilder,
}

impl ConflictResolutionClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type().expect(
            "ConflictResolution is statically defined in .baml and should always have a type",
        )
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `resolved` field builder.
    pub fn property_resolved(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("resolved")
            .expect("ConflictResolution.resolved is statically defined in .baml and should always be present")
    }

    /// Access the `needs_human` field builder.
    pub fn property_needs_human(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("needs_human")
            .expect("ConflictResolution.needs_human is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `ResolvedConflict` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ResolvedConflictClassBuilder {
    inner: baml::ClassBuilder,
}

impl ResolvedConflictClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner
            .as_type()
            .expect("ResolvedConflict is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `path` field builder.
    pub fn property_path(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("path").expect(
            "ResolvedConflict.path is statically defined in .baml and should always be present",
        )
    }

    /// Access the `content` field builder.
    pub fn property_content(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("content").expect(
            "ResolvedConflict.content is statically defined in .baml and should always be present",
        )
    }

    /// Access the `confidence` field builder.
    pub fn property_confidence(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("confidence")
            .expect("ResolvedConflict.confidence is statically defined in .baml and should always be present")
    }

    /// Access the `rationale` field builder.
    pub fn property_rationale(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("rationale")
            .expect("ResolvedConflict.rationale is statically defined in .baml and should always be present")
    }
}
