pub const DEFAULT_COVERAGE_THRESHOLD: f64 = 80.0;

pub mod affected;
pub mod audit;
pub mod cache;
pub mod check_deps;
pub mod check_freshness;
pub mod ci;
pub mod clean;
pub mod config;
pub mod dev_setup;
pub mod discovery;
pub mod fmt;
pub mod hooks;
pub mod lint;
pub mod progress;
pub mod protocol;
pub mod quick;
pub mod runner;
pub mod step;
pub mod testing;
pub mod update_claude;
pub mod util;
pub mod version;
